trigger:
  - main

pool:
  name: matanAgent  # Ensure this matches your self-hosted agent pool name

variables:
  buildConfiguration: 'Release'
  artifactName: 'matan-feed'  # Ensure this matches your Azure Artifacts feed name
  artifactVersion: '1.0.$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
              export PATH="$PATH:$HOME/.dotnet"
            displayName: 'Install .NET SDK'

          - script: |
              curl -fsSL https://aka.ms/install-artifacts-credprovider.sh | bash
            displayName: 'Install Azure Artifacts Credential Provider'

          - script: |
              dotnet restore
            displayName: 'Restore NuGet Packages'

          - script: |
              dotnet build --configuration $(buildConfiguration)
            displayName: 'Build Project'

          - script: |
              dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(artifactVersion)
            displayName: 'Pack Project into NuGet Package'

          - script: |
              dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source $(artifactName) --api-key $(System.AccessToken)
            displayName: 'Publish NuGet Package to Azure Artifacts'
            env:
              NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
