trigger:
  - main

pool:
  name: matanAgent  

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: 'restore'
              projects: './azure-helloWorld.csproj'
            displayName: 'Restore dependencies'

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'
              projects: './azure-helloWorld.csproj'
              arguments: '--configuration Release'
            displayName: 'Build project'
  