trigger:
  - main

pool:
  name: matanAgent

variables:
  buildConfiguration: 'Release'
  artifactName: 'matan-feed'  # Ensure this matches your Azure Artifacts feed name

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '6.x'  # Specify the .NET SDK version as needed

          - task: NuGetAuthenticate@1
            displayName: 'Authenticate with Azure Artifacts'

          - script: |
              dotnet restore
            displayName: 'Restore NuGet Packages'

          - script: |
              dotnet build --configuration $(buildConfiguration)
            displayName: 'Build Project'

          - script: |
              dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
            displayName: 'Pack Project into NuGet Package'

          - task: DotNetCoreCLI@2
            displayName: 'Publish NuGet Package to Azure Artifacts'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              nuGetFeedType: 'internal'
              publishVstsFeed: 'matan-feed'
