# azure-pipelines.yml

trigger:
- main

pool:
  name: matanAgent  # Custom self-hosted agent

stages:
- stage: Build
  jobs:
    - job: BuildJob
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '7.x.x'  # Specify the .NET version you need (e.g., 6.x.x, 7.x.x)

        - script: dotnet build ./azure-helloworld.csproj --configuration Release
          displayName: 'Build project'

