trigger:
  - main

pool:
  name: matanAgent  

variables:
  buildConfiguration: 'Release'
  artifactName: 'matan-feed'  
  artifactVersion: '1.0.$(Build.BuildId)'

jobs:
  - job: Build_Job
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'  
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet Tool'
    
    - task: NuGetAuthenticate@1
      displayName: 'Authenticate with NuGet'
    
    - task: NuGetAuthenticate@1
      displayName: 'Authenticate with Azure Artifacts'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: './azure-helloWorld.csproj'
      displayName: 'Restore Dependencies'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: './azure-helloWorld.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'Build Project'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        projects: './azure-helloWorld.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      displayName: 'Pack The Project'

    - script: |
          dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source $(artifactName) --api-key $(System.AccessToken)
          displayName: 'Publish NuGet Package to Azure Artifacts'
          env:
          NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
