trigger:
  - main

pool:
  name: matanAgent

variables:
  buildConfiguration: 'Release'
  artifactName: 'feed-matan'
  artifactVersion: '1.0.$(Build.BuildId)'

jobs:
  - job: Build_Job
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tool'
        inputs:
          versionSpec: '5.x'

      - task: NuGetAuthenticate@1
        displayName: 'Authenticate with Azure Artifacts'

      - task: DotNetCoreCLI@2
        displayName: 'Restore Dependencies'
        inputs:
          command: 'restore'
          projects: './azure-helloWorld.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build Project'
        inputs:
          command: 'build'
          projects: './azure-helloWorld.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Pack Project'
        inputs:
          command: 'pack'
          projects: './azure-helloWorld.csproj'
          outputDir: '$(Build.ArtifactStagingDirectory)'

      
      - task: DotNetCoreCLI@2
        inputs:
          arguments: '--skip-duplicate'
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '92d7f46c-db9b-4ce4-9eb9-1d02c9b3e668/7443abf4-fbf7-43fa-9b0a-800e4e335c00'
        displayName: 'Push nupkg to Artifact'

