trigger:
  - main

pool:
  name: matanAgent  

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              dotnet build  --configuration Release
              dotnet pack . --configuration Release
            displayName: 'Build project'
        

          - task: NuGetCommand@2
            inputs:
              command: 'push'
              publishVstsFeed: 'matan-feed'
              packageFile: '$(Build.ArtifactStagingDirectory)/*.nupkg'
              versioningScheme: 'off'
              versionPublish: $(artifactVersion)
            displayName: 'Publish NuGet Package to Azure Artifacts'

          
            