# azure-pipelines.yml

trigger:
- main

pool:
  name: matanAgent  # Custom self-hosted agent
<<<<<<< HEAD

stages:
- stage: CreateEnv
  jobs:
    - job: SetupEnvironment
      steps:
        - script: |
            python -m venv myenv
            source myenv/bin/activate
            python -m pip install --upgrade pip
          displayName: 'Create and activate virtual environment'

- stage: Build
  dependsOn: CreateEnv
  jobs:
    - job: BuildJob
      steps:
        - script: |
            source myenv/bin/activate
            dotnet build ./azure-helloworld.csproj --configuration Release
          displayName: 'Build project'
=======

stages:
- stage: Build
  jobs:
    - job: BuildJob
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '7.x.x'  # Specify the .NET version you need (e.g., 6.x.x, 7.x.x)

        - script: dotnet build ./azure-helloworld.csproj --configuration Release
          displayName: 'Build project'

>>>>>>> 266a730c175e92109fc8a14839a8f316bc5193f1
