trigger:
  - main

pool:
  name: matanAgent

variables:
  buildConfiguration: 'Release'
  artifactName: 'matan-feed'  # Ensure this matches your Azure Artifacts feed name

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '6.x'  # Specify the .NET SDK version as needed

          - task: UseNode@1
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '14.x'  # Specify the Node.js version as needed

          - script: |
              npm install
            displayName: 'Install Node.js Dependencies'

          - script: |
              npx commitizen init cz-conventional-changelog --save-dev --save-exact
            displayName: 'Initialize Commitizen'

          - script: |
              npx cz --version
            displayName: 'Verify Commitizen Installation'

          - task: NuGetAuthenticate@1
            displayName: 'Authenticate with Azure Artifacts'

          - script: |
              dotnet restore
            displayName: 'Restore NuGet Packages'

          - script: |
              dotnet build --configuration $(buildConfiguration)
            displayName: 'Build Project'

          - script: |
              dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
            displayName: 'Pack Project into NuGet Package'

          - script: |
              dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source $(artifactName) --api-key $(System.AccessToken)
            displayName: 'Publish NuGet Package to Azure Artifacts'
            env:
              NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
