trigger:
  - main

pool:
  name: matanFeed

variables:
  buildConfiguration: 'Release'
  artifactName: 'matanFeed'
  artifactVersion: '1.0.$(Build.BuildId)'

jobs:
  - job: Build_Job
    steps:
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tool'
        inputs:
          versionSpec: '5.x'

      - task: NuGetAuthenticate@1
        displayName: 'Authenticate with Azure Artifacts'

      - task: DotNetCoreCLI@2
        displayName: 'Restore Dependencies'
        inputs:
          command: 'restore'
          projects: './azure-helloWorld.csproj'
          feedsToUse: 'select'
          vstsFeed: 'feed-matan'

      - task: DotNetCoreCLI@2
        displayName: 'Build Project'
        inputs:
          command: 'build'
          projects: './azure-helloWorld.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Pack Project'
        inputs:
          command: 'pack'
          projects: './azure-helloWorld.csproj'
          arguments: '--configuration $(buildConfiguration)'
          outputDir: '$(Build.ArtifactStagingDirectory)'

      - task: NuGetCommand@2
        displayName: 'Push to Feed'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '$(artifactName)'
