trigger:
  - main

pool:
  name: matanAgent  

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: |
              ls -ltr
              dotnet build ./azure-helloworld.csproj --configuration Release
            displayName: 'Build project'
