trigger:
  - main

pool:
  name: matanAgent

variables:
  buildConfiguration: 'Release'
  artifactName: 'feed-matan'
  artifactVersion: '1.0.$(Build.BuildId)-$(Build.SourceBranchName)'
  jdkFile: '/home/ubuntu/temp/jre-8u431-linux-x64.tar.gz'

jobs:
  - job: Build_Job
    steps:
      - checkout: self
        fetchDepth: 0
      - script: |
          git pull git@github.com:MatanKaufman1/hello_world_azure.git

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tool'

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '21'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'LocalDirectory'
          jdkFile: $(jdkFile)
      

      - task: NuGetAuthenticate@1
        displayName: 'Authenticate with Azure Artifacts'

      - task: DotNetCoreCLI@2
        displayName: 'Restore Dependencies'
        inputs:
          command: 'restore'
          projects: '/home/ubuntu/_work/1/workdir/azure-helloWorld.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build Project'
        inputs:
          command: 'build'
          projects: '/home/ubuntu/_work/1/workdir/azure-helloWorld.csproj'
          arguments: '--configuration $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: 'Pack Project'
        inputs:
          command: 'pack'
          projects: './azure-helloWorld.csproj'
          outputDir: '$(Build.ArtifactStagingDirectory)'
          versioningScheme: 'byEnvVar'
          versionEnvVar: artifactVersion

      - task: DotNetCoreCLI@2
        displayName: 'Push nupkg to Artifact'
        inputs:
          command: 'push'
          packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: '92d7f46c-db9b-4ce4-9eb9-1d02c9b3e668/7443abf4-fbf7-43fa-9b0a-800e4e335c00'