# azure-pipelines.yml

trigger:
- main

pool:
  name: matanAgent  

stages:
- stage: CreateEnv
  jobs:
    - job: SetupEnvironment
      steps:
        - script: |
            python -m venv myenv
            source myenv/bin/activate
            python -m pip install --upgrade pip
          displayName: 'Create and activate virtual environment'

- stage: Build
  dependsOn: CreateEnv
  jobs:
    - job: BuildJob
      steps:
        - script: |
            source myenv/bin/activate
            dotnet build ./azure-helloworld.csproj --configuration Release
          displayName: 'Build project'

