trigger:
  - main

pool:
  name: matanAgent  

jobs:
  - job: Build_Job
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.x'  
        installationPath: $(Agent.ToolsDirectory)/dotnet
      displayName: 'Install .NET SDK'

    - task: NuGetToolInstaller@1
      displayName: 'Install NuGet Tool'
    
    - task: NuGetAuthenticate@1
      displayName: 'Authenticate with NuGet'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: './azure-helloWorld.csproj'
      displayName: 'Restore Dependencies'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: './azure-helloWorld.csproj'
        arguments: '--configuration Release'
      displayName: 'Build Project'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        projects: './azure-helloWorld.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    displayName: 'Pack The Project'
