trigger:
  - main

pool:
  name: matanAgent

variables:
  buildConfiguration: 'Release'
  artifactName: 'feed-matan'
  artifactVersion: '1.0.$(Build.BuildId)-$(Build.SourceBranchName)'
  jdkFile: '/home/ubuntu/temp/jre-8u431-linux-x64.tar.gz'

jobs:
  - job: Build_Job
    steps:
      - checkout: self
        fetchDepth: 0

      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          installationPath: $(Agent.ToolsDirectory)/dotnet

      - task: NuGetToolInstaller@1
        displayName: 'Install NuGet Tool'

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '21'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'LocalDirectory'
          jdkFile: '$(jdkFile)'

      - task: NuGetAuthenticate@1
        displayName: 'Authenticate with Azure Artifacts'

      - task: SonarQubePrepare@6
        inputs:
          SonarQube: 'SonarQube'
          scannerMode: 'MSBuild'
          organization: 'matankaufman1'
          projectKey: 'matankaufman1_hello-world-azure'
          projectName: 'hello-world-azure'
        displayName: 'Prepare SonarQube Analysis'

      - task: DotNetCoreCLI@2
        displayName: 'Restore Dependencies'
        inputs:
          command: 'restore'
          projects: '/home/ubuntu/azure-helloWorld.csproj'

      - task: DotNetCoreCLI@2
        displayName: 'Build Project'
        inputs:
          command: 'build'
          projects: '/home/ubuntu/azure-helloWorld.csproj'
          arguments: '--configuration $(buildConfiguration)'

      
      - task: SonarQubePublish@6
        displayName: 'Publish SonarQube Results'
        inputs:
          pollingTimeoutSec: '300'

      - script: |
            dotnet pack /home/ubuntu/azure-helloWorld.csproj  --configuration Release --output $(artifactVersion)
        displayName: 'Pack NuGet Package'






      - script: |
          dotnet nuget push /home/ubuntu/bin/Release/*.nupkg.$(artifactVersion) --source "https://pkgs.dev.azure.com/matankaufman1/hello-world-azure/_packaging/feed-matan/nuget/v3/index.json" --api-key $(System.AccessToken)
        displayName: 'Push NuGet Package to Azure Artifacts'