trigger:
  - main

pool:
  name: matanAgent  

variables:
  buildConfiguration: 'Release'
  artifactName: 'matan-feed'  # Ensure this matches your Azure Artifacts feed name
  artifactVersion: '1.0.$(Build.BuildId)'

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
            displayName: 'Install .NET SDK'

        
          - task: gittools.gitversion.gitversion-task.GitVersion@5
            displayName: 'Execute GitVersion'
            inputs:
              useConfigFile: true
              configFilePath: 'GitVersion.yml'  # Path to your GitVersion.yml file


          - task: NuGetAuthenticate@1
            displayName: 'Authenticate with Azure Artifacts'

          - script: |
              dotnet restore
            displayName: 'Restore NuGet Packages'

          - script: |
              dotnet build --configuration $(buildConfiguration)
            displayName: 'Build Project'

          - script: |
              dotnet pack --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(artifactVersion)
            displayName: 'Pack Project into NuGet Package'

          - script: |
              dotnet nuget push $(Build.ArtifactStagingDirectory)/*.nupkg --source $(artifactName) --api-key $(System.AccessToken)
            displayName: 'Publish NuGet Package to Azure Artifacts'
            env:
              NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true

          
            